### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by anggimude** [Chay-HyunminPark/Anxiety_depressive_disorder#1]
- title and subtitle is well organized and written 
- author and date exists and is up to date
- abstract is well written; it is clear what will be done in the paper and how it will effect potential audience
- introduction is great as it explains what will be done in each part of the paper in a specific manner.
- graphs that are produced seem great
- simulate, data-cleaning, testing are all done outstandingly

- you could change the name of the paper to something more related to the intended study
- it may be better to read and write the raw data in the download_data section after giving the instructions. 

overall this repo seems like a great first draft. hope you keep up the work.

**Comment by Chay-HyunminPark** [comment]
Check points

you could change the name of the paper to something more related to the intended study

it may be better to read and write the raw data in the download_data section after giving the instructions.
