### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by RayanAlim** [Chay-HyunminPark/Anxiety_depressive_disorder#2]
- Great title and abstract both informative, your ReadMe is super clear on how to reproduce of paper and navigate if repo which is very comprehensive. The ReadME title and the paper title are different, would be good to stick to one version and apply throughout. 

- Expanding on the significance of this dataset and how it may be used or why it’s needed/ a nice addition to the world would add more depth to your analysis. You touch on the gap that exists but not so why it needs to be filled.

- You have good visualizations, just need to clean up the legends and formatting a bit more 

- Some sections are not finished, but I'm sure it will be completed soon. 

Best of luck with this paper, looks good so far!

**Comment by Chay-HyunminPark** [comment]
Check point

Expanding on the significance of this dataset and how it may be used or why it’s needed/ a nice addition to the world would add more depth to your analysis. You touch on the gap that exists but not so why it needs to be filled.
